# Generates logos_build_info.h — baked into both the app binary and the
# main UI plugin so version + commit hashes can be printed to logs on startup
# and rendered on the Dashboard view.
{ pkgs, buildInfo }:

pkgs.writeText "logos_build_info.h" ''
  // Auto-generated by nix/build-info.nix — do not edit.
  #pragma once

  #define LOGOS_BASECAMP_VERSION "${buildInfo.version}"

  namespace logos_basecamp_build_info {
      inline constexpr const char* kCommitsJson = R"LOGOSJSON(${builtins.toJSON buildInfo.commits})LOGOSJSON";
  }
''
