# Builds the main UI plugin
{ pkgs, common, src, logosSdk, logosModule, logosPackageManagerModule, logosLiblogos, logosViewModuleRuntime, buildInfo, distributed ? false }:

let
  buildInfoHeader = import ./build-info.nix { inherit pkgs buildInfo; };
in
pkgs.stdenv.mkDerivation {
  pname = "${common.pname}-main-ui-plugin";
  version = common.version;
  
  inherit src;
  inherit (common) buildInputs meta;
  
  # Add logosSdk to nativeBuildInputs for logos-cpp-generator
  nativeBuildInputs = common.nativeBuildInputs ++ [ logosSdk ];
  
  preConfigure = ''
    runHook prePreConfigure

    # Set macOS deployment target to match Qt frameworks
    export MACOSX_DEPLOYMENT_TARGET=12.0

    # Create generated_code directory for generated files
    mkdir -p ./src/generated_code

    # Drop the auto-generated build info header (version + commit hashes) so
    # MainUIBackend can expose it to QML for the Dashboard.
    cp ${buildInfoHeader} ./src/generated_code/logos_build_info.h
    chmod +w ./src/generated_code/logos_build_info.h

    # Note: we deliberately do NOT stage a partial cpp-sdk copy under
    # ./logos-cpp-sdk/ any more. The CMakeLists now uses
    # `find_package(logos-cpp-sdk CONFIG PATHS
    # $LOGOS_CPP_SDK_ROOT/lib/cmake/logos-cpp-sdk)`, which carries
    # include dirs + the link interface (OpenSSL, Boost, nlohmann_json)
    # via the imported target. Pointing LOGOS_CPP_SDK_ROOT directly at
    # the SDK store path (set in configurePhase below) means the
    # *Config.cmake files are present where find_package looks.

    # Copy module-generated API files from logos-package-manager-module
    echo "Copying include files from logos-package-manager-module..."
    if [ -d "${logosPackageManagerModule}/include" ]; then
      echo "Found include directory in logos-package-manager-module"
      cp -r "${logosPackageManagerModule}/include"/* ./src/generated_code/
      echo "Copied include files:"
      ls -la ./src/generated_code/
    else
      echo "Warning: No include directory found in logos-package-manager-module"
    fi

    # Run logos-cpp-generator with metadata.json and --general-only flag
    echo "Running logos-cpp-generator (general-only) for main_ui..."
    logos-cpp-generator --metadata ${src}/metadata.json --general-only --output-dir ./src/generated_code
    
    # Check what was generated by logos-cpp-generator
    echo "Checking generated files in generated_code:"
    ls -la ./src/generated_code/
    
    # Don't move any files - keep everything in generated_code root for simplicity
    # The logos_sdk.h includes them with bare names like "core_manager_api.h"
    echo "Files in generated_code:"
    ls -la ./src/generated_code/
    
    # For nix builds, we don't need to create the logos-cpp-sdk/cpp/generated structure
    # since we're using the installed SDK layout and linking against the SDK library
    echo "Using installed SDK layout - generated files are for reference only"
    
    runHook postPreConfigure
  '';
  
  configurePhase = ''
    runHook preConfigure
    
    echo "Configuring main UI plugin..."
    echo "logosSdk: ${logosSdk}"
    echo "logosModule: ${logosModule}"
    echo "logosLiblogos: ${logosLiblogos}"

    # Verify that the logosSdk exists
    test -d "${logosSdk}" || (echo "logosSdk not found" && exit 1)
    test -d "${logosModule}" || (echo "logosModule not found" && exit 1)
    test -d "${logosLiblogos}" || (echo "logosLiblogos not found" && exit 1)
    
    cmake -S src -B build \
      -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
      -DLOGOS_DISTRIBUTED_BUILD=${if distributed then "ON" else "OFF"} \
      -DLOGOS_PORTABLE_BUILD=${if distributed then "ON" else "OFF"} \
      -DLOGOS_CPP_SDK_ROOT=${logosSdk} \
      -DLOGOS_MODULE_ROOT=${logosModule} \
      -DLOGOS_LIBLOGOS_ROOT=${logosLiblogos} \
      -DLOGOS_VIEW_MODULE_RUNTIME_ROOT=${logosViewModuleRuntime}
    
    runHook postConfigure
  '';
  
  buildPhase = ''
    runHook preBuild
    
    cmake --build build
    echo "Main UI plugin built successfully!"
    
    runHook postBuild
  '';
  
  installPhase = ''
    runHook preInstall
    
    mkdir -p $out/lib
    
    # Find and copy the built library file
    if [ -f "build/main_ui.dylib" ]; then
      cp build/main_ui.dylib $out/lib/
    elif [ -f "build/main_ui.so" ]; then
      cp build/main_ui.so $out/lib/
    else
      echo "Error: No main_ui library file found"
      exit 1
    fi
    
    runHook postInstall
  '';
}
